version: "3.0"

services:
  postgresqldg:
    image: postgres:9.3
    env_file: .env
    volumes:
      - ./dockerfiles/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"

  project:
    tty: true
    build: ./
    command: sh start.sh
    env_file: .env
    working_dir: /opt/project
    volumes:
      - ./src:/opt/project
    links:
      - postgresqldg
    ports:
      - "8000:8000"